basePath: /api/v1
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: pasindu@tuta.com
    name: API Support
    url: https://github.com/MasterBrian99/bukmarq
  description: Server Implementation
  license:
    name: MIT
    url: https://opensource.org/license/mit/
  termsOfService: https://github.com/MasterBrian99/bukmarq
  title: Bukmarq Backend Server
  version: 0.0.1
paths:
  /healthcheck:
    get:
      consumes:
      - application/json
      description: do health check
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: health check
      tags:
      - example
securityDefinitions:
  Authentication:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
